name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest] #We are not doing [ubuntu-latest] right now since the project is not mature enough to publish a snap
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: NPM or Yarn install with caching
      uses: bahmutov/npm-install@v1.1.0
    - name: Electron Builder Action
      uses: samuelmeuli/action-electron-builder@v1.3.0
      with:
        # GitHub authentication token: 
          github_token: ${{ secrets.github_token }}

          #mac_certs: # optional
          #Password for decrypting `mac_certs`
          #mac_certs_password: # optional:  
          release: true
          
     
