name: CI

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: NPM or Yarn install with caching
      uses: bahmutov/npm-install@v1.1.0
    - name: Electron Builder Action
      uses: samuelmeuli/action-electron-builder@v1.3.0
      with:
        # GitHub authentication token: 
          github_token: ${{ secrets.github_token }}

          #mac_certs: # optional
          #Password for decrypting `mac_certs`
          #mac_certs_password: # optional:  
          release: true
          
     
